In [7]:
import numpy as np
a = [1,2,3,4,5]
b = [3,6,9,12,15]
aa = np.array(a)
ab = np.array(b)
a,b

([1, 2, 3, 4, 5], [3, 6, 9, 12, 15])

# numpy calculation
## support:

1. +
1. -
1. *
1. /
1. %
1. **

In [8]:
aa+ab, aa-ab, aa*ab, ab/aa, ab+5%aa+2, ab**aa

(array([ 4,  8, 12, 16, 20]),
 array([ -2,  -4,  -6,  -8, -10]),
 array([ 3, 12, 27, 48, 75]),
 array([3, 3, 3, 3, 3]),
 array([ 5,  9, 13, 15, 17]),
 array([     3,     36,    729,  20736, 759375]))

In [14]:
aa.mean(), aa.std(), np.median(ab)

(3.0, 1.4142135623730951, 9.0)