[View in Colaboratory](https://colab.research.google.com/github/reaganwei0216/data/blob/master/kuo.ipynb)

In [1]:
from random import sample

sample(range(1, 21), k=1)

[16]

In [6]:
print("Hello 104!")

Hello 104!


test

In [7]:
tony = "Iron Man"
print(tony)

Iron Man


In [9]:
tony.upper()

'IRON MAN'

## 如何使用 Google Colaboratory

In [0]:
steve = "Captain America"

In [11]:
steve.split(sep=" ")

['Captain', 'America']

In [13]:
type(steve.split(sep=" "))

list

In [0]:
?range

In [19]:
#@title 我最喜歡的漫威英雄

fav_hero = "bbb" #@param ["aaa", "bbb"]
print("我最喜歡的漫威英雄是{}".format(fav_hero))

我最喜歡的漫威英雄是bbb


In [21]:
#@title 給復仇者聯盟三：無限之戰一個分數，從 0 到 10

avengers_3_rating = 100 #@param {type:"slider", min:0, max:100, step:10}
print("我給復仇者聯盟三的分數是 {}".format(avengers_3_rating))

我給復仇者聯盟三的分數是 6.7


In [0]:
def get_bmi(height, weight):
  """
  告知使用者的 BMI 與指標
  """
  bmi = weight / (height*0.01)**2
  if bmi < 18.5:
    label = "Underweight"
  elif 18.5 <= bmi < 25:
    label = "Normal"
  elif 25 <= bmi < 30:
    label = "Overweight"
  else:
    label = "Obese"
  return bmi, label

In [0]:
?get_bmi

In [24]:
get_bmi(172, 65)

(21.971335857220122, 'Normal')

In [25]:
my_bmi, my_label = get_bmi(172, 65)
print("我的 BMI 是 {:.2f}，指標是 {}".format(my_bmi, my_label))

我的 BMI 是 21.97，指標是 Normal


In [26]:
!pip install numpy

In [32]:
import numpy as np

heights = [175, 170, 165, 160, 155]
weights = [50, 55, 60, 65, 70]
bmis = []
for h, w in zip(heights, weights):
  bmis.append(w/(h*0.01)**2)
print(bmis)
type(bmis)

[16.3265306122449, 19.031141868512112, 22.038567493112943, 25.390624999999996, 29.1363163371488]


list

In [30]:
heights_arr = np.array(heights)
weights_arr = np.array(weights)
bmis = weights_arr / (heights_arr*0.01)**2
print(bmis)
type(bmis)

[16.32653061 19.03114187 22.03856749 25.390625   29.13631634]


numpy.ndarray

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10).reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
type(np.arange(24).reshape(2, 3, 4))

numpy.ndarray

In [38]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
!pip install pandas

In [40]:
import pandas as pd

avengers = ["Iron Man", "Captain America", "Black Panther"]
characters = ["Tony Stark", "Steve Rogers", "T'Challa"]
df = pd.DataFrame()
df["avenger"] = avengers
df["character"] = characters
df

avenger     character
0         Iron Man    Tony Stark
1  Captain America  Steve Rogers
2    Black Panther      T'Challa

In [41]:
type(df)

pandas.core.frame.DataFrame

In [42]:
df['avenger']

0           Iron Man
1    Captain America
2      Black Panther
Name: avenger, dtype: object

In [43]:
type(df["avenger"])

pandas.core.series.Series

In [44]:
type(df["avenger"].values)

numpy.ndarray

In [45]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [46]:
df["character"] == "Tony Stark"

0     True
1    False
2    False
Name: character, dtype: bool

In [48]:
df[df["character"] == "Tony Stark"]

avenger   character
0  Iron Man  Tony Stark

In [49]:
!pip install pyquery

    100% |████████████████████████████████| 5.9MB 6.5MB/s 


In [54]:
from pyquery import PyQuery as pq

rating_css = "strong span"
html_doc = pq("https://www.imdb.com/title/tt4154756")
rating = html_doc(rating_css).text()
rating = float(rating)
rating

8.8

In [0]:
from pyquery import PyQuery as pq

def get_movie_info(movie_url):
  """
  get movie info
  """
  rating_css = "strong span"
  genre_css = ".subtext .itemprop"
  cast_css = ".itemprop .itemprop"
  html_doc = pq(movie_url)
  rating = html_doc(rating_css).text()
  rating = float(rating)
  rating
  genre = [g.text for g in html_doc(genre_css)]
  genre
  cast = [c.text for c in html_doc(cast_css)]
  movie_info = {
      "rating": rating,
      "genre": genre,
      "cast": cast
  }
  return(movie_info)

In [56]:
get_movie_info("https://www.imdb.com/title/tt4154756")

{'cast': ['Robert Downey Jr.',
  'Chris Hemsworth',
  'Mark Ruffalo',
  'Chris Evans',
  'Scarlett Johansson',
  'Don Cheadle',
  'Benedict Cumberbatch',
  'Tom Holland',
  'Chadwick Boseman',
  'Zoe Saldana',
  'Karen Gillan',
  'Tom Hiddleston',
  'Paul Bettany',
  'Elizabeth Olsen',
  'Anthony Mackie'],
 'genre': ['Action', 'Adventure', 'Fantasy'],
 'rating': 8.8}

In [57]:
get_movie_info("https://www.imdb.com/title/tt1825683")

{'cast': ['Chadwick Boseman',
  'Michael B. Jordan',
  "Lupita Nyong'o",
  'Danai Gurira',
  'Martin Freeman',
  'Daniel Kaluuya',
  'Letitia Wright',
  'Winston Duke',
  'Sterling K. Brown',
  'Angela Bassett',
  'Forest Whitaker',
  'Andy Serkis',
  'Florence Kasumba',
  'John Kani',
  'David S. Lee'],
 'genre': ['Action', 'Adventure', 'Sci-Fi'],
 'rating': 7.5}