In [ ]:
import tensorflow as tf

In [ ]:
layer = tf.keras.layers.Dense(100)
layer(tf.zeros([1, 1])) #x,y

<tf.Tensor: shape=(1, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)>

In [ ]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))
layer(tf.zeros([1, 1])) #x,y

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
layer.weights, layer.bias

([<tf.Variable 'dense_17/kernel:0' shape=(1, 10) dtype=float32, numpy=
  array([[-0.21599352, -0.01159245, -0.32844064, -0.52657735, -0.01830393,
           0.52513224,  0.6424678 , -0.3000843 , -0.5981913 , -0.07481587]],
        dtype=float32)>,
  <tf.Variable 'dense_17/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>],
 <tf.Variable 'dense_17/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [ ]:
class JerryDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(JerryDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                         self.num_outputs])

  def call(self, input):
    return tf.matmul(input, self.kernel)


In [ ]:
layer = JerryDenseLayer(10)
layer(tf.zeros([1, 1])) #x,y

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>