In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
csv_data = tf.keras.utils.get_file('iris.csv', 'https://raw.githubusercontent.com/jerrywu2013/Hiskio_data/master/iris.csv')

8192/3975 [=============================================================] - 0s 1us/step


In [3]:
df = pd.read_csv(csv_data)

In [4]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [5]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [6]:
#轉換目標欄位為離散值
df['variety'] = pd.Categorical(df['variety'])

In [7]:
df.dtypes

sepal.length     float64
sepal.width      float64
petal.length     float64
petal.width      float64
variety         category
dtype: object

In [9]:
df['variety'] = df.variety.cat.codes

In [10]:
df.head()

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [11]:
#透過tf.data.Dataset做資料切割與轉換

In [12]:
target = df.pop('variety')

In [13]:
df.values

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
target.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int8)

In [15]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [16]:
#透過tf.data.Dataset可以轉換標準的Tensor資料管道方便之後運算
dataset

<TensorSliceDataset shapes: ((4,), ()), types: (tf.float64, tf.int8)>

In [18]:
#觀察資料
for i in dataset.take(20):
  print (i)
  print()

(<tf.Tensor: id=58, shape=(4,), dtype=float64, numpy=array([5.1, 3.5, 1.4, 0.2])>, <tf.Tensor: id=59, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=60, shape=(4,), dtype=float64, numpy=array([4.9, 3. , 1.4, 0.2])>, <tf.Tensor: id=61, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=62, shape=(4,), dtype=float64, numpy=array([4.7, 3.2, 1.3, 0.2])>, <tf.Tensor: id=63, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=64, shape=(4,), dtype=float64, numpy=array([4.6, 3.1, 1.5, 0.2])>, <tf.Tensor: id=65, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=66, shape=(4,), dtype=float64, numpy=array([5. , 3.6, 1.4, 0.2])>, <tf.Tensor: id=67, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=68, shape=(4,), dtype=float64, numpy=array([5.4, 3.9, 1.7, 0.4])>, <tf.Tensor: id=69, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=70, shape=(4,), dtype=float64, numpy=array([4.6, 3.4, 1.4, 0.3])>, <tf.Tensor: id=71, shape=(), dtype=int8, numpy=0>)

(<tf.Tensor: id=72, shape=(4,), dtype=float64, numpy=ar

In [19]:
#將資料根據資料列數進行shuffle
all_train_dataset = dataset.shuffle(len(df)).batch(1)

In [20]:
#觀察資料
for i in all_train_dataset.take(20):
  print (i)
  print()  

(<tf.Tensor: id=114, shape=(1, 4), dtype=float64, numpy=array([[6. , 3. , 4.8, 1.8]])>, <tf.Tensor: id=115, shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)

(<tf.Tensor: id=116, shape=(1, 4), dtype=float64, numpy=array([[6.7, 3.3, 5.7, 2.5]])>, <tf.Tensor: id=117, shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)

(<tf.Tensor: id=118, shape=(1, 4), dtype=float64, numpy=array([[5.7, 2.5, 5. , 2. ]])>, <tf.Tensor: id=119, shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)

(<tf.Tensor: id=120, shape=(1, 4), dtype=float64, numpy=array([[4.8, 3. , 1.4, 0.3]])>, <tf.Tensor: id=121, shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)

(<tf.Tensor: id=122, shape=(1, 4), dtype=float64, numpy=array([[5.7, 2.9, 4.2, 1.3]])>, <tf.Tensor: id=123, shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)

(<tf.Tensor: id=124, shape=(1, 4), dtype=float64, numpy=array([[5.8, 2.7, 5.1, 1.9]])>, <tf.Tensor: id=125, shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)

(<tf.Tensor: id=

In [ ]:
train_dataset = all_train_dataset.take(int(0.7 * len(df)))
test_dataset = all_train_dataset.skip(int(0.7 * len(df)))

In [ ]:
for i in test_dataset.take(20):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.8, 2.7, 3.9, 1.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.9, 3. , 5.1, 1.8]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.4, 3.7, 1.5, 0.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.7, 2.6, 3.5, 1. ]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.7, 4.4, 1.5, 0.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.7, 3.3, 5.7, 2.1]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.5, 3. , 5.5, 1.8]])>, <tf.Tensor: shape=(1,), dtype=int8, nu

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3)
])

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) 
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(train_dataset, epochs=10)

Epoch 1/10
105/105 [==============================] - 1s 919us/step - loss: 1.2478 - accuracy: 0.2873
Epoch 2/10
105/105 [==============================] - 0s 924us/step - loss: 0.8328 - accuracy: 0.6573
Epoch 3/10
105/105 [==============================] - 0s 1ms/step - loss: 0.6077 - accuracy: 0.7214
Epoch 4/10
105/105 [==============================] - 0s 1ms/step - loss: 0.5616 - accuracy: 0.6617
Epoch 5/10
105/105 [==============================] - 0s 1ms/step - loss: 0.4857 - accuracy: 0.8640
Epoch 6/10
105/105 [==============================] - 0s 1ms/step - loss: 0.4259 - accuracy: 0.8322
Epoch 7/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3707 - accuracy: 0.7939
Epoch 8/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3426 - accuracy: 0.8878
Epoch 9/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3553 - accuracy: 0.9271
Epoch 10/10
105/105 [==============================] - 0s 1ms/step - loss: 0.2587 - accuracy: 0.

In [ ]:
model.evaluate(test_dataset)

45/45 [==============================] - 0s 809us/step - loss: 0.2238 - accuracy: 0.9778


[0.22379349172115326, 0.9777777791023254]

In [ ]:
for i in test_dataset.take(1):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.4, 3.4, 1.5, 0.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)


In [ ]:
pred = model.predict([[5.4, 3.4, 1.5, 0.4]])
np.argmax(pred)

0