In [4]:
import pandas as pd
import requests
import io
import os
import numpy as np

In [5]:
store = [["burgers","meatballs","eggs"],
      ["turkey","burgers","mineral water","cooking oil"],
      ["burgers","grated cheese","pasta","honey","toothpaste"],
      ["meatballs","milk","eggs","honey","french fries","protein bar"],
      ["red wine","shrimp","pasta","pepper","eggs","chocolate","shampoo"],
      ["burgers","black tea","green tea"],
      ["burgers","black tea","green tea"],
      ["burgers","meatballs","eggs"],
      ["burgers","meatballs","eggs"],
      ["burgers","meatballs","eggs"],
      ["escalope","burgers","shallot"],
      ["red wine","shrimp","pasta","pepper","eggs","chocolate","shampoo"],
      ["spaghetti","milk","french fries","green tea"]]

In [6]:
store

[['burgers', 'meatballs', 'eggs'],
 ['turkey', 'burgers', 'mineral water', 'cooking oil'],
 ['burgers', 'grated cheese', 'pasta', 'honey', 'toothpaste'],
 ['meatballs', 'milk', 'eggs', 'honey', 'french fries', 'protein bar'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['burgers', 'black tea', 'green tea'],
 ['burgers', 'black tea', 'green tea'],
 ['burgers', 'meatballs', 'eggs'],
 ['burgers', 'meatballs', 'eggs'],
 ['burgers', 'meatballs', 'eggs'],
 ['escalope', 'burgers', 'shallot'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['spaghetti', 'milk', 'french fries', 'green tea']]

## 先驗演算法(Apriori Algorithm)



In [9]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [10]:
apriori_Encoder = TransactionEncoder()
apriori_Encoder_Array = apriori_Encoder.fit(store).transform(store)

In [11]:
apriori_Encoder_Array

array([[False,  True, False, False,  True, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False,  True, False,  True, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False,  True],
       [False,  True, False, False, False, False, False,  True, False,
         True, False, False, False,  True, False, False, False, False,
        False, False, False,  True, False],
       [False, False, False, False,  True, False,  True, False, False,
         True,  True,  True, False, False, False,  True, False, False,
        False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False, False,
        False, False, False, False,  True,  True, False,  True, False,
         True,  True, False, False, False],
       [ True,  True, False, False, False, False, False, False,  True,

In [13]:
type(apriori_Encoder_Array)

numpy.ndarray

In [14]:
apriori_Encoder_Array.shape

(13, 23)

In [12]:
apriori_Encoder.columns_

['black tea',
 'burgers',
 'chocolate',
 'cooking oil',
 'eggs',
 'escalope',
 'french fries',
 'grated cheese',
 'green tea',
 'honey',
 'meatballs',
 'milk',
 'mineral water',
 'pasta',
 'pepper',
 'protein bar',
 'red wine',
 'shallot',
 'shampoo',
 'shrimp',
 'spaghetti',
 'toothpaste',
 'turkey']

In [16]:
df = pd.DataFrame(apriori_Encoder_Array, columns=apriori_Encoder.columns_)
df

black tea  burgers  chocolate  cooking oil   eggs  escalope  french fries  \
0       False     True      False        False   True     False         False   
1       False     True      False         True  False     False         False   
2       False     True      False        False  False     False         False   
3       False    False      False        False   True     False          True   
4       False    False       True        False   True     False         False   
5        True     True      False        False  False     False         False   
6        True     True      False        False  False     False         False   
7       False     True      False        False   True     False         False   
8       False     True      False        False   True     False         False   
9       False     True      False        False   True     False         False   
10      False     True      False        False  False      True         False   
11      False    False       True        False   True     False         False   
12      False    False      False        False  False     False          True   

    grated cheese  green tea  honey  ...  pasta  pepper  protein bar  \
0           False      False  False  ...  False   False        False   
1           False      False  False  ...  False   False        False   
2            True      False   True  ...   True   False        False   
3           False      False   True  ...  False   False         True   
4           False      False  False  ...   True    True        False   
5           False       True  False  ...  False   False        False   
6           False       True  False  ...  False   False        False   
7           False      False  False  ...  False   False        False   
8           False      False  False  ...  False   False        False   
9           False      False  False  ...  False   False        False   
10          False      False  False  ...  False   False        False   
11          False      False  False  ...   True    True        False   
12          False       True  False  ...  False   False        False   

    red wine  shallot  shampoo  shrimp  spaghetti  toothpaste  turkey  
0      False    False    False   False      False       False   False  
1      False    False    False   False      False       False    True  
2      False    False    False   False      False        True   False  
3      False    False    False   False      False       False   False  
4       True    False     True    True      False       False   False  
5      False    False    False   False      False       False   False  
6      False    False    False   False      False       False   False  
7      False    False    False   False      False       False   False  
8      False    False    False   False      False       False   False  
9      False    False    False   False      False       False   False  
10     False     True    False   False      False       False   False  
11      True    False     True    True      False       False   False  
12     False    False    False   False       True       False   False  

[13 rows x 23 columns]

In [18]:
apriori(df, min_support=0.2, use_colnames=False)

support    itemsets
0  0.692308         (1)
1  0.538462         (4)
2  0.230769         (8)
3  0.384615        (10)
4  0.230769        (13)
5  0.307692      (1, 4)
6  0.307692     (1, 10)
7  0.384615     (10, 4)
8  0.307692  (1, 10, 4)

In [17]:
apriori(df, min_support=0.2, use_colnames=True)

support                    itemsets
0  0.692308                   (burgers)
1  0.538462                      (eggs)
2  0.230769                 (green tea)
3  0.384615                 (meatballs)
4  0.230769                     (pasta)
5  0.307692             (burgers, eggs)
6  0.307692        (burgers, meatballs)
7  0.384615           (eggs, meatballs)
8  0.307692  (burgers, eggs, meatballs)

## 協同過濾演算法(Collaborative Filtering) - 基於使用者

In [19]:
from collections import defaultdict,Counter
import numpy as np
import math
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
store = [["burgers","meatballs","eggs"],
      ["turkey","burgers","mineral water","cooking oil"],
      ["burgers","grated cheese","pasta","honey","toothpaste"],
      ["meatballs","milk","eggs","honey","french fries","protein bar"],
      ["red wine","shrimp","pasta","pepper","eggs","chocolate","shampoo"],
      ["burgers","black tea","green tea"],
      ["burgers","black tea","green tea"],
      ["burgers","meatballs","eggs"],
      ["burgers","meatballs","eggs"],
      ["burgers","meatballs","eggs"],
      ["escalope","burgers","shallot"],
      ["red wine","shrimp","pasta","pepper","eggs","chocolate","shampoo"],
      ["spaghetti","milk","french fries","green tea"]]

In [21]:
df = pd.DataFrame(apriori_Encoder_Array, columns=apriori_Encoder.columns_)
df

black tea  burgers  chocolate  cooking oil   eggs  escalope  french fries  \
0       False     True      False        False   True     False         False   
1       False     True      False         True  False     False         False   
2       False     True      False        False  False     False         False   
3       False    False      False        False   True     False          True   
4       False    False       True        False   True     False         False   
5        True     True      False        False  False     False         False   
6        True     True      False        False  False     False         False   
7       False     True      False        False   True     False         False   
8       False     True      False        False   True     False         False   
9       False     True      False        False   True     False         False   
10      False     True      False        False  False      True         False   
11      False    False       True        False   True     False         False   
12      False    False      False        False  False     False          True   

    grated cheese  green tea  honey  ...  pasta  pepper  protein bar  \
0           False      False  False  ...  False   False        False   
1           False      False  False  ...  False   False        False   
2            True      False   True  ...   True   False        False   
3           False      False   True  ...  False   False         True   
4           False      False  False  ...   True    True        False   
5           False       True  False  ...  False   False        False   
6           False       True  False  ...  False   False        False   
7           False      False  False  ...  False   False        False   
8           False      False  False  ...  False   False        False   
9           False      False  False  ...  False   False        False   
10          False      False  False  ...  False   False        False   
11          False      False  False  ...   True    True        False   
12          False       True  False  ...  False   False        False   

    red wine  shallot  shampoo  shrimp  spaghetti  toothpaste  turkey  
0      False    False    False   False      False       False   False  
1      False    False    False   False      False       False    True  
2      False    False    False   False      False        True   False  
3      False    False    False   False      False       False   False  
4       True    False     True    True      False       False   False  
5      False    False    False   False      False       False   False  
6      False    False    False   False      False       False   False  
7      False    False    False   False      False       False   False  
8      False    False    False   False      False       False   False  
9      False    False    False   False      False       False   False  
10     False     True    False   False      False       False   False  
11      True    False     True    True      False       False   False  
12     False    False    False   False       True       False   False  

[13 rows x 23 columns]

In [22]:
for u in df.columns:
  if df[u].dtype==bool:
    df[u]=df[u].astype('int')

In [23]:
df

black tea  burgers  chocolate  cooking oil  eggs  escalope  french fries  \
0           0        1          0            0     1         0             0   
1           0        1          0            1     0         0             0   
2           0        1          0            0     0         0             0   
3           0        0          0            0     1         0             1   
4           0        0          1            0     1         0             0   
5           1        1          0            0     0         0             0   
6           1        1          0            0     0         0             0   
7           0        1          0            0     1         0             0   
8           0        1          0            0     1         0             0   
9           0        1          0            0     1         0             0   
10          0        1          0            0     0         1             0   
11          0        0          1            0     1         0             0   
12          0        0          0            0     0         0             1   

    grated cheese  green tea  honey  ...  pasta  pepper  protein bar  \
0               0          0      0  ...      0       0            0   
1               0          0      0  ...      0       0            0   
2               1          0      1  ...      1       0            0   
3               0          0      1  ...      0       0            1   
4               0          0      0  ...      1       1            0   
5               0          1      0  ...      0       0            0   
6               0          1      0  ...      0       0            0   
7               0          0      0  ...      0       0            0   
8               0          0      0  ...      0       0            0   
9               0          0      0  ...      0       0            0   
10              0          0      0  ...      0       0            0   
11              0          0      0  ...      1       1            0   
12              0          1      0  ...      0       0            0   

    red wine  shallot  shampoo  shrimp  spaghetti  toothpaste  turkey  
0          0        0        0       0          0           0       0  
1          0        0        0       0          0           0       1  
2          0        0        0       0          0           1       0  
3          0        0        0       0          0           0       0  
4          1        0        1       1          0           0       0  
5          0        0        0       0          0           0       0  
6          0        0        0       0          0           0       0  
7          0        0        0       0          0           0       0  
8          0        0        0       0          0           0       0  
9          0        0        0       0          0           0       0  
10         0        1        0       0          0           0       0  
11         1        0        1       1          0           0       0  
12         0        0        0       0          1           0       0  

[13 rows x 23 columns]

In [31]:
 df.iloc[0,].to_numpy()

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [29]:
 df.iloc[0,].to_numpy().shape

(23,)

In [32]:
df.iloc[0,].to_numpy().reshape(1, -1)

array([[0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]])

In [30]:
df.iloc[0,].to_numpy().reshape(1, -1).shape

(1, 23)

In [24]:
a = df.iloc[0,].to_numpy().reshape(1, -1)
b = df.iloc[1,].to_numpy().reshape(1, -1)
cosine_similarity(a, b)

array([[0.28867513]])

In [33]:
user_a = df.iloc[0,].to_numpy().reshape(1, -1)
new=[]
for i in range(0,12):
  b = df.iloc[i,].to_numpy().reshape(1, -1)
  similarity_matrix = cosine_similarity(user_a, b)
  new = np.append(new, similarity_matrix)

df.iloc[np.where(new)],new


(    black tea  burgers  chocolate  cooking oil  eggs  escalope  french fries  \
 0           0        1          0            0     1         0             0   
 1           0        1          0            1     0         0             0   
 2           0        1          0            0     0         0             0   
 3           0        0          0            0     1         0             1   
 4           0        0          1            0     1         0             0   
 5           1        1          0            0     0         0             0   
 6           1        1          0            0     0         0             0   
 7           0        1          0            0     1         0             0   
 8           0        1          0            0     1         0             0   
 9           0        1          0            0     1         0             0   
 10          0        1          0            0     0         1             0   
 11          0        0     

In [ ]:
#https://raw.githubusercontent.com/jerrywu2013/Hiskio_data/master/store_data.csv